import { v4 as uuidv4 } from "uuid";

const data = [
  {
    id: uuidv4(),
    content: "وعادي بنحس بالوجع يصحبي صحبي مش شايفك جدع يا صحبي",
    category: "rap",
    song: "العين",
  },
  {
    id: uuidv4(),
    content: "محدش قالي كدة غلط كدة عيب",
    category: "rap",
    song: "العين",
  },
  {
    id: uuidv4(),
    content: "بابا جيهه ف اي جيهه يجييها",
    category: "rap",
    song: "عفاريت الاسفلت",
  },
  {
    id: uuidv4(),
    content: "مكنش له لزمة هقل منك مش أزمة",
    category: "rap",
    song: "عفاريت الاسفلت",
  },
  {
    id: uuidv4(),
    content: "بدون ماستأذن ادور واحرق",
    category: "rap",
    song: "عفاريت الاسفلت",
  },
  {
    id: uuidv4(),
    content: "زميلي شطبنا الدايرة اكتملت مش ناقصين عشان انتو ناقصين",
    category: "rap",
    song: "عفاريت الاسفلت",
  },
  {
    id: uuidv4(),
    content: "شربت كاس المر ومين يدفع التمن",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "مش قادر اعايش الواقع مش قادر انافق العالم",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "نمنا صحينا بقينا نجوم",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: " منحبش اللي يغطرسها فقير لله وبفنطظها ",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "كبرنا واتوحشنا عشان نعامل البشر ",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "بنزاملوا الرجال وبناكل بالحلال",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content:
      "رايحة بينا فين ماشية بينا كام سلكنا من ناب القرش ومسلكناش ف العلام",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "صاحبي مفيش بشر غيرنا ٧ مليار وانا ف وحدة",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "كبرنا واتوحشنا عشان نعامل البشر",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "ديما اسرح ف السكة زميلي العمر بيفوت",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "ف راسك يتحكموا ف حقك يتحججوا",
    category: "rap",
    song: "سكرتي",
  },
  {
    id: uuidv4(),
    content: "شعر طويل اكحل بتدور",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "اسف ياما مسلكتش ف التعليم بس راجل عمري ما جليت زميلي",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "انا وانا وانا من غيرك ولا حاجة لازم بيك",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "جروح القلوب منفعاش عيادة",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "قولتلها مش بحبك وانتي عادة",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "مش حاطط في بالي ساليني الدنيا انا ساليها وبتساليني",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "انتي خدعة كبيرة جمالك مزيف",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "تكدبي تقولي بموت فيك وانتي حية",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "للرصيف بشكي همي للرصيف",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "معادنا كان جميل نقتطين الشتا اسكندرية ف الخريف",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "العلاقة ديه كانت ضرب نار ليه انا الوحيد اللي بتصاب",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "الجروح بيعالوجها ف صيدلية وانا اعالج جروحي بالاصحاب",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "اسف صاحبي مباصيش غير جوبات",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content: "وشي مميز تشرب عشان تنساه",
    category: "rap",
    song: "ساليني",
  },
  {
    id: uuidv4(),
    content:
      "الجروح بيعالوجها ف صيدلية وانا اعالج جروحي بالاصحابستني وتسيبي ايدي تبعدي وتضحكيلي تهمسي وتقوليلي احنا اصلا مش لبعض",
    category: "rap",
    song: "تايه",
  },
  {
    id: uuidv4(),
    content:
      " بعد ايام سوده تحنيلي كلك بتوحشيني فاكره اني هقبل برجوعك عشان شايفه حبي ضعف",
    category: "rap",
    song: "تايه",
  },
  {
    id: uuidv4(),
    content: "محدش شافني ضعيف .. وسيبته يعيش جراح قلوب وكمادات قلبي الحشيش",
    category: "rap",
    song: "تايه",
  },
  {
    id: uuidv4(),
    content: "دلوقتي بتقولي احنا نرجع بيبي ليه فاكرها لعبه",
    category: "rap",
    song: "تايه",
  },
  {
    id: uuidv4(),
    content: "مش عايز دكتور عايز ATM",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "محدش عارفك بس صاحبتك مشهورة",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "دباديب عاملين عصابة توي ستوري",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "بتكلمني بتاع ايه  هجاص بوشين ",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: " ملحة ف عينك حسود  كسول نجم وصاعد مكوك صاروخ ",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "اكون او لا اكون",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "قلبي وعقلي ف صراع وانا بتقسم نصين",
    category: "rap",
    song: "ATM",
  },
  {
    id: uuidv4(),
    content: "ف قفصي محبوس ف ضياع",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "عيني عطشانة وعايزة تشوف",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "سابق سني سابق زمني",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "لا مش رجلي صاحبي طرفي ع السين",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "زميلي زوري يأكل عيش ويفتح شركة",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "الحفلة كلها صفرة من جوه علي حسابي شوتات ديتول",
    category: "rap",
    song: "نصين",
  },
  {
    id: uuidv4(),
    content: "بصحى أعيش ف كوابيس",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "بحور فلوس ناطط فيها",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "حضرلي سلطه نشتري فلوس حضرلي نفوذ و الباقي بتاعي",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "بشر تعابين عايزين رفاعيي",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "الماضي الي مطاردني وحوش جوة مني",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "دايره حرب اصاحبي و انا الي بموت",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "لو غمضت تعيش اللحظه لو فتحت تعيش كابوس",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "",
    category: "rap",
    song: "بولا بولا",
  },
  {
    id: uuidv4(),
    content: "عايزاني احكي ومداريش وانا مداري سراديب ",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "عيون كتير وكلام كتير مفيش غيري ف الكواليس",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "بتراضي دماغك بتفتفت ف حبوب",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "كان واقف بينا الكلام ومش واقف النزيف",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "ونترمي ف الشبك عيونك صيادين",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "مخسرتكيش اللا لو خسرتك برصاصة",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "نجروا ف سباق مع الزمن ومين غيري بيدفع التمن",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "كان عندي قلب اتهلك",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content:
      "الدروب مسدودة والافواه مفتوحة الابواب مقفولة والفرص محدودة الوشوش كدابة والوشوش مكشوفة ",
    category: "rap",
    song: "كان نفسي",
  },
  {
    id: uuidv4(),
    content: "كلنا بنعاني تيجي عليا ليه يعني",
    category: "rap",
    song: "منحوس",
  },
  {
    id: uuidv4(),
    content: "اتعايش مع ماضيك قبل ما تعيب ع الناس التانيه",
    category: "rap",
    song: "منحوس",
  },
  {
    id: uuidv4(),
    content: "عيني منها بشكل جدى ",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "ياخى كنت ع الثبات وهزتني",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "انا بالى معاها مش ملكى",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "عارفنى صعب ومش مفهوم",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "ملاك برئ ولا انا مخدوع",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "انسيك ماضى كله دموع ولا مقدرش اسيبك موجوع",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "سحرتنى ولا سحرتلى",
    category: "rap",
    song: "",
  },
  {
    id: uuidv4(),
    content: "مش عايزة تجيبنى بس جابتنى",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content:
      "والله ووقعت بفكر فيك كتير بالى عليك مشغول وانا بتصعب عليا حالى وانا بكتبلك كلام معسول",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "براحه على قلبي المكسور اللى مشكلته أنه فيك مسحول",
    category: "rap",
    song: "البخت",
  },
  {
    id: uuidv4(),
    content: "حواري بتربي والدنيا بتعلم",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "متأمنش للزمن ابطال بتكتف",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "اروح بيها لو عيني فيها",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "يحكموا عليك من فيشك",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "دنيا بوشين .. لابسه القناع",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "رحلة البحث عن اللضي",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content: "مفيش حلول ف الطبق نفركوا المر .. مفيش غير سم ف الطبق",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content:
      "مفيش غير حلم واترفض .. نص الاحمر يترفع .. وجروحنا مش بتداوي .. مفيش حل ف اتاوة",
    category: "rap",
    song: "حواري",
  },
  {
    id: uuidv4(),
    content:
      "راسي مدينة ، شوارعها ذكريات عندي زمايلي جبروته ، يتاجروا في الممنوعات",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "مفيش وقت لو همشي لابس ٥ ساعات",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "مش كتير هيساعدوك ، طول الطريق",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "الأحلام مجاناً وانا حلمت اكون أمير",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "تيجي وتروح احنا صحاب المطرح",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "حرام ف اكياس حلال بالقطرة",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "٢١ ولساني ٦٠ ولساني سكين",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "الله بيبعت كتير  ،عشان  على قد النية",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "الله بيبعت كتير  ،عشان  على قد النية",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content:
      "لسه بياخدوني بالشكل لسه بكتب اغنيه احط فيها الاماال والهم اللي فيا",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content:
      "اصحابي رجالة ،اصحابي عتالة اصحابي يا دولة  ، من هنا لبكره احكي وما اوفيش ",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "جوانا شياكه قد حكام الامارات نفسي الفرصه تجيلنا واحنا ف البارات",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "متأمنيش انك هستبيني ف حالة وترجعي ف نفس الحالة",
    category: "rap",
    song: "21",
  },
  {
    id: uuidv4(),
    content: "تحياتي للي كنت بعتبرهم اخواتي لم يعد الأمر كذلك",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content: "كيفي كده، كيفي هنا واللي أقوله هنمشيه",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content:
      "خذت السكة الصعبة وحفظت أنا الكراسة عندي أشقة أبالسة تموت إن ضعف إخلاصك",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content: "كلام كثير ملوش داعي أحفر حفرة وأدفن أوجاعي",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content:
      "عاجباك إعتبرها مقاسك عيش عيش بقى بإحساسك عيش وسيبها تعيش شباب طباعها حداثة، طباعكم خباثة",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content: "ياه طلعتوا فالصو طلعتوا عيرة",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content: "وارد أنساك إبقى فكرني",
    category: "rap",
    song: "كيفي كده",
  },
  {
    id: uuidv4(),
    content: "بفِّتنا تعاشر المظابيط يا سمك شعرة يا مصابيح",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "لو إنت بابا طب أنا مين؟",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "قلِّبت الحلو النسكويك صدري واسع وأحتويك",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content:
      "الشغل شغل الحق صنعة العين بالعين والديّة طلقة شَمال أفارقة الحركة بركة وشك دواسة أدوس تكركر",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "إنتوا عالرفوف والشماعات",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "أنا سني صغير عمري قصير طفولة جافة عليك أتغير",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "آه يا غزالتي يا سهرانة",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "كعوبي نايكي وغدارات",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "من غير ما أتمرّن يابا أول جمهورية",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "وارث كافكا قائد مافيا",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "البطن شابعة، النية صافية العين مليانة، زاهدة راضية",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content:
      "حسينا الغيرة عامياهم حسوا الزمن مر سنين كتير بيلكوا وحالهم ولا يسر",
    category: "rap",
    song: "دورك جي",
  },
  {
    id: uuidv4(),
    content: "صحابي رجاله مفلس بصيح عمري محسيت عمري بيضيع",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "انتي مش وحيده قلبي بيصيع  راسك مسمم عايزه جديد",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "انا مش ملاك  بس انتي شيطانه",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content:
      "مش انا اللي اتكلبش مش انا اللي اتمنتج بيبي بطل فيلمك سوبر ستار ياااه",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "نفضل نتكلم ونهرج ونصدع نحب ونتجرح ونتصاب ونقرر نودع نودع ",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "كان لازم تمشي قبل ما الحرب ما تبتدي ماتبتدي",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "مش  واجعني اني بايع كانت بتشتري",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "اللي فاضل فيا مش كتير",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content:
      "واعيش ادور علي السبب  واموت مش لاقي تفسير اعيش بطاوع الزمن  بكره احلي وربنا كبير",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "واتربينا علي الشقي وكبرنا بنسال ع الشيك",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "انا سم اوعي تحبيني",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "بدور علي نصي انا في معاناه",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "انا مصاب احنا في معاناة",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "شاب وحزين بس نجم  ع البوستر",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content:
      "Fu*ck fame  Fu*ck love  Fu*ck fake friends Bit*ches love us We love benz Get me paid to buy that shit She got me shoes And booze and i only got her that di*ck alone  Got her that di*ck",
    category: "rap",
    song: "حورية",
  },
  {
    id: uuidv4(),
    content: "كلها دايرة ع المصلحة",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "فاكر إنك تقدر تاخذ مني حاجة تبقى مجنون ومن هنا ع المصحة",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "تحت العشرين وأدي لك دروس حياة صاحبنا الجناة وزملينا الأشقيا",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "كلميني اتناشر لما الدنيا تروق كلميني اتناشر لما الظلمة تسود",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "غلطاتك بتعلقها على شماعة الظروف",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "ألحاني حزينة كمان مكسور",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "أنا في المدينة دي كتاب مفتوح همشي لبعيد لحد أما توه",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "عايشها في الظلمة ومشوفتش نور بارد وعشانك أنا دمي يفور",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "شعري طويل أكحل بتدور",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "قتلت النوم في عيوني كل يوم بالليل",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "حياتي عاملة زي النزهة بجد فكرت أقلبها فيلم",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content:
      "الواقع ممكن يطلع كذب شيطاني في راسي بيفرز سم الواقع ممكن يطلع حلم",
    category: "rap",
    song: "دايرة علي المصلحة",
  },
  {
    id: uuidv4(),
    content: "مش فاضيلك نجم ومش فاضيلك بيننا سور لا تجيلي ولا أجيلك",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "صاحبي قصة حياتي أنا مألفها فـ أوضتي",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "أنا مش زي حد فيهم مش بتنسا",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "انتي بتحبيني وأنا أحب الإزازة",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "مين كان يصدق شاغلة بالي وروحي فيها",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "حبيتك أكتر من الأغاني اللي بغنيها",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "شاغل بالي العشرين سنة جروا فـ يوم",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "مشغول بناقش قلبي ندور عـ بديلك",
    category: "rap",
    song: "ساليني 2",
  },
  {
    id: uuidv4(),
    content: "عمرنا ما إتبترنا  عمرنا ما استكرتنا ",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "متظبطلوا العداد مبقاش حمل حسابو",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "عشان الكل عاملي وحوش قال يعني حجرة مبيحسوش ",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "متفوقولنا بقا جدع تلعب بالنار تدفع التمن",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "زمانكو راح زماني إبتدأ",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "عاوج نفسي قوي بس عادل الكاب",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content: "فاكر نفسك علم عامل نفسك انا عالم في النفسنه عالم ع السكسكة",
    category: "rap",
    song: "اسياد الصوت",
  },
  {
    id: uuidv4(),
    content:
      "مقلناش مع حد يا حاسدين الغير في عينكوا خرزة زرقاء لو ما تحبوليش الخير",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "أخوك يكسح بارباروسا بجي بي إل",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "الراجل ما يعيبوش غير جيب دي كانت كذبة كله ياخذ على عينه",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "إنت ما بتتقدرش أخوك ما بيتقدرش",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "بفتنا على القمة راشد على الإنتاج عندي جوز أنياب نادر زي العاج",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "اكمني كثير البخت ومش قليل كلام",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "ملناش في الديفنس ذهاب بلا عودة",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "بكرة تفوق وتفهم بس مش هتروق وتحلى",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "مش حمل كتفي هنلاعبك مع حد قدك",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "لسه مجبتش ربع اولي جبت آخرك",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "طول ما فيّ رجل هنشوط في كله",
    category: "rap",
    song: "مش فير",
  },
  {
    id: uuidv4(),
    content: "مين عداني ومتوترش",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content: "متكترش نقلوا منك ومنقدرش  تستغرب ليه بتشب ومبتوصلش ",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content: "علمنا عليكوا وعلمناكوا",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content:
      "محدثين بقالي سنين بلعب لوحدي فمتجيش  تقولي سين اللي بنلمحه بنمرجحه فمتجيش ",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content: "طب كان فين الغل مني لما كنا قريبين",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content: "عرفنا انك قلة بتتسند ع الشلة",
    category: "rap",
    song: "هصلا",
  },
  {
    id: uuidv4(),
    content: "احنا نجوم كدة كدة عملنا فلوس كدة كدة ",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "في اللي نفسه يبقي رقم واحد ومش جايه معاه اننا لسه عايش ",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "اقوي انسان ف المدينة",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "تولعوها عواد كبريت علي قدكو نولعوها بنزينة ",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "حارق الحقودين ف الهولوكوست",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "تنساني ازاي وانا ع البيلبورد",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "احنا استوينا انت لسه ني",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "بلعب مع الكبار انت صغير",
    category: "rap",
    song: "كدا كدا",
  },
  {
    id: uuidv4(),
    content: "ما تسعناش إحنا الإثنين",
    category: "rap",
    song: "باظت",
  },
  {
    id: uuidv4(),
    content: "بسهولة بجيبها وبوديها",
    category: "rap",
    song: "باظت",
  },
  {
    id: uuidv4(),
    content: "إحنا كوابيس تشوفنا تقول يا لطيف",
    category: "rap",
    song: "باظت",
  },
  {
    id: uuidv4(),
    content: "شوارعي كئيبة دماغي غريبة",
    category: "rap",
    song: "مدينة المذنبين",
  },
  {
    id: uuidv4(),
    content: "مستنانيش غير الموت مفيش غير ضلمة ومفيش صوت",
    category: "rap",
    song: "مدينة المذنبين",
  },
  {
    id: uuidv4(),
    content:
      "مدينة مهجورة والهوا قلاب لو فيها هتحس انك وحيد فالكون ياريتك داري أن الأفضل وحيد",
    category: "rap",
    song: "مدينة المذنبين",
  },
  {
    id: uuidv4(),
    content: "الخوف بيحاوطك الضلمة حضناك متحاوطين بسور كلهم أشرار",
    category: "rap",
    song: "مدينة المذنبين",
  },
];
data.sort((a, b) => 0.5 - Math.random());
export default data;
